### ISSUE TITLE
Buggy temperature responses?

### ISSUE THREAD

**Issue by admiral96** [ZeevG/python-forecast.io#44]
I tried to use this library and it was a success, it worked but the problem is that when I queried for the temperature for New York, it shows somewhat like 53°C which is not true but its 53°F. Other places have right responses like Cebu, Philippines and shows 29°C or something which is true. It might be just me but thanks in advance for clarifying on this one

**Comment by bzillins** [comment]
Admiral,

This is expected behavior as forecast.io "selects the relevant units automatically, based on geographic location."

You can force the data returned to be consistently in a certain set of units by setting the units flag.

Example

Celsius:
load_forecast(key, lat, lng, time=None, units="**si**", lazy=False, callback=None):

Fahrenheit:
load_forecast(key, lat, lng, time=None, units="**us**", lazy=False, callback=None):

**Comment by admiral96** [comment]
Thanks for clarifying :)
